import { ReactElement, ReactNode } from "react";
// import Alert from "../components/alert";
// import Footer from "../components/footer";
// import Meta from "../components/meta";

type LayoutProps = {
  children: JSX.Element | JSX.Element[]
}

export default function Layout({children}:LayoutProps) {
  return (
    <>
    
      <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      <div className="min-h-screen">
        <main>{children}</main>
      </div>
   
    </>
  );
}
