import React from 'react'

function Meta() {
    return (
        <>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </>
    )
}

export default Meta